### ISSUE TITLE
Styles as submodules are changing

### ISSUE THREAD

**Issue by klokan** [klokantech/tileserver-gl-styles#1]
gh-pages are forced pushed by Travis.

If people try to rebuild this npm package - it will be broken.

We have to link to a release - or push a local copy of the style or better solve version management.

**Comment by klokan** [comment]
The first release zip will contain already JSONs with 3 fonts - which will not run as we distribute only one font with the NPM package.

Be careful on a new release to NPM until this is solved...

**Comment by petrsloup** [comment]
Yes, but that's nothing new, right? It was already implemented before -- we always keep only the first font reference in the styles (which should be Open Sans):
https://github.com/klokantech/tileserver-gl-styles/blob/master/publish.js#L36

**Comment by klokan** [comment]
OK. Sorry. I thought we rely on a submodule in git. In the time where this npm module was released our generated JSON styles had only one font inside. Fair enough. Thanks! Closing.
